<#
.SYNOPSIS
  claude-video-kit installer for Windows (PowerShell 5.1+ / 7+).

.DESCRIPTION
  Installs ffmpeg / Python / Node / yt-dlp via winget, creates a private venv with a
  Whisper engine, links the skills into %USERPROFILE%\.claude\skills, installs the `vk`
  launcher, and registers the blueprint MCP server. Idempotent — safe to re-run.

.PARAMETER Engine
  Whisper engine to install: faster (default, no PyTorch) | openai | none

.PARAMETER Copy
  Copy the skills instead of creating directory junctions.

.PARAMETER WithHyperframes
  Also install the HyperFrames authoring skill pack from upstream (npx hyperframes skills).

.PARAMETER NoMcp
  Skip MCP server registration.

.PARAMETER NoDeps
  Skip winget package installation.

.PARAMETER Yes
  Non-interactive: assume yes.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File install\install.ps1
#>
[CmdletBinding()]
param(
  [ValidateSet('faster', 'openai', 'none')][string]$Engine = 'faster',
  [switch]$Copy,
  [switch]$WithHyperframes,
  [switch]$NoMcp,
  [switch]$NoDeps,
  [switch]$Yes
)

$ErrorActionPreference = 'Stop'

$Kit       = Split-Path -Parent $PSScriptRoot
$ClaudeDir = if ($env:CLAUDE_CONFIG_DIR) { $env:CLAUDE_CONFIG_DIR } else { Join-Path $HOME '.claude' }
$SkillsDir = Join-Path $ClaudeDir 'skills'
$Venv      = Join-Path $Kit '.venv'
$BinDir    = Join-Path $ClaudeDir 'bin'

function Write-Bold($m) { Write-Host $m -ForegroundColor White }
function Write-Info($m) { Write-Host "  · $m" -ForegroundColor Cyan }
function Write-Ok  ($m) { Write-Host "  + $m" -ForegroundColor Green }
function Write-Warn2($m){ Write-Host "  ! $m" -ForegroundColor Yellow }
function Write-Err ($m) { Write-Host "  x $m" -ForegroundColor Red }

function Confirm-Step($question) {
  if ($Yes) { return $true }
  $a = Read-Host "  ? $question [Y/n]"
  return ($a -eq '' -or $a -match '^[Yy]')
}

function Test-Cmd($name) { return [bool](Get-Command $name -ErrorAction SilentlyContinue) }

Write-Bold "claude-video-kit installer (Windows)"
Write-Info "kit: $Kit"

# ── 1 · system dependencies via winget ─────────────────────────────────────
Write-Bold "1/6 system dependencies"
if ($NoDeps) {
  Write-Info "-NoDeps: skipping winget packages"
} elseif (-not (Test-Cmd winget)) {
  Write-Warn2 "winget not found. Install manually: ffmpeg, Python 3.11+, Node 22+, yt-dlp"
} else {
  $pkgs = @(
    @{ Cmd = 'ffmpeg';  Id = 'Gyan.FFmpeg' },
    @{ Cmd = 'python';  Id = 'Python.Python.3.12' },
    @{ Cmd = 'node';    Id = 'OpenJS.NodeJS.LTS' },
    @{ Cmd = 'yt-dlp';  Id = 'yt-dlp.yt-dlp' }
  )
  foreach ($p in $pkgs) {
    if (Test-Cmd $p.Cmd) { Write-Ok "$($p.Cmd) present"; continue }
    if (Confirm-Step "install $($p.Cmd) ($($p.Id)) with winget?") {
      winget install --id $p.Id --accept-source-agreements --accept-package-agreements -e --silent
      Write-Ok "$($p.Cmd) installed (a new shell may be needed for PATH)"
    } else {
      Write-Warn2 "$($p.Cmd) skipped"
    }
  }
}

# ── 2 · python venv + whisper engine ───────────────────────────────────────
Write-Bold "2/6 whisper engine ($Engine)"
if ($Engine -eq 'none') {
  Write-Info "skipped by -Engine none"
} else {
  $py = if (Test-Cmd python) { 'python' } elseif (Test-Cmd py) { 'py' } else { $null }
  if (-not $py) {
    Write-Err "python not found — install it and re-run"
  } else {
    if (-not (Test-Path $Venv)) { & $py -m venv $Venv }
    $vpy = Join-Path $Venv 'Scripts\python.exe'
    & $vpy -m pip install --quiet --upgrade pip
    switch ($Engine) {
      'faster' { & $vpy -m pip install --quiet faster-whisper; Write-Ok "faster-whisper (CTranslate2, no torch)" }
      'openai' { & $vpy -m pip install --quiet openai-whisper; Write-Ok "openai-whisper (PyTorch — large download)" }
    }
    Write-Info "venv: $Venv  (models download on first use)"
  }
}

# ── 3 · vk launcher ────────────────────────────────────────────────────────
Write-Bold "3/6 vk launcher"
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$launcher = @"
@echo off
REM claude-video-kit launcher (generated by install.ps1)
set "KIT=$Kit"
if exist "%KIT%\.venv\Scripts\python.exe" (
  "%KIT%\.venv\Scripts\python.exe" "%KIT%\bin\vk.py" %*
) else (
  python "%KIT%\bin\vk.py" %*
)
exit /b %ERRORLEVEL%
"@
Set-Content -Path (Join-Path $BinDir 'vk.cmd') -Value $launcher -Encoding ASCII
Write-Ok (Join-Path $BinDir 'vk.cmd')

$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if ($userPath -notlike "*$BinDir*") {
  if (Confirm-Step "add $BinDir to your user PATH?") {
    [Environment]::SetEnvironmentVariable('Path', "$userPath;$BinDir", 'User')
    Write-Ok "PATH updated (new terminals only)"
  } else {
    Write-Warn2 "call it with the full path: $BinDir\vk.cmd"
  }
}

# ── 4 · skills ─────────────────────────────────────────────────────────────
Write-Bold "4/6 skills -> $SkillsDir"
New-Item -ItemType Directory -Force -Path $SkillsDir | Out-Null
Get-ChildItem -Path (Join-Path $Kit 'skills') -Directory | ForEach-Object {
  $name = $_.Name
  $dest = Join-Path $SkillsDir $name
  if (Test-Path $dest) {
    $item = Get-Item $dest -Force
    $isLink = $item.LinkType -in @('Junction', 'SymbolicLink')
    if (-not $isLink -and -not $Copy) {
      if (Confirm-Step "$name exists as a real folder — replace it with a junction to the kit?") {
        Move-Item $dest "$dest.bak-$(Get-Date -Format yyyyMMddHHmmss)"
      } else { Write-Info "$name kept, skipped"; return }
    } else {
      Remove-Item $dest -Recurse -Force
    }
  }
  if ($Copy) {
    Copy-Item $_.FullName $dest -Recurse
    Write-Ok "$name (copy)"
  } else {
    # directory junctions do NOT require admin rights or developer mode
    New-Item -ItemType Junction -Path $dest -Target $_.FullName | Out-Null
    Write-Ok "$name (junction)"
  }
}

@{ kitPath = $Kit; installedAt = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ss') } |
  ConvertTo-Json | Set-Content -Path (Join-Path $ClaudeDir 'video-kit.json') -Encoding UTF8
Write-Ok (Join-Path $ClaudeDir 'video-kit.json')

# ── 5 · MCP servers ────────────────────────────────────────────────────────
Write-Bold "5/6 MCP servers"
if ($NoMcp) {
  Write-Info "-NoMcp: skipped"
} elseif (-not (Test-Cmd claude)) {
  Write-Warn2 "claude CLI not found — register manually later:"
  Write-Host  "        claude mcp add blueprint -s user -- npx -y @railsblueprint/blueprint-mcp@latest"
} else {
  # `mcp get` is exact and fast; `mcp list` health-checks every server
  claude mcp get blueprint *> $null
  if ($LASTEXITCODE -eq 0) {
    Write-Ok "blueprint already registered"
  } elseif (Confirm-Step "register the blueprint MCP server (browser automation) for your user?") {
    claude mcp add blueprint -s user -- npx -y '@railsblueprint/blueprint-mcp@latest'
    Write-Ok "blueprint registered"
  }
}

# ── 6 · optional HyperFrames pack ──────────────────────────────────────────
Write-Bold "6/6 HyperFrames authoring pack (optional)"
if ($WithHyperframes) {
  if (Test-Cmd npx) { npx -y hyperframes@latest skills; Write-Ok "HyperFrames skill pack installed by upstream" }
  else { Write-Warn2 "npx not found — install Node 22+, then: npx hyperframes skills" }
} else {
  Write-Info "skipped (pass -WithHyperframes to install it from upstream)"
}

Write-Host ""
& (Join-Path $BinDir 'vk.cmd') doctor
Write-Host ""
Write-Bold "Done. Restart Claude Code so it picks up the new skills."
